// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0atI_X2v3lYO6vreCiRJIcZHcmYRI4QQ',
    appId: '1:643613146881:web:6e00eb6750a6bd7e16a500',
    messagingSenderId: '643613146881',
    projectId: 'flutterinstagramclone-284ee',
    authDomain: 'flutterinstagramclone-284ee.firebaseapp.com',
    storageBucket: 'flutterinstagramclone-284ee.appspot.com',
    measurementId: 'G-MKZGPJL7N6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbcTQHo3aTKOJ0njO-nwHVkUNtMPImMgY',
    appId: '1:643613146881:android:3bcd5a93bc2cbf0516a500',
    messagingSenderId: '643613146881',
    projectId: 'flutterinstagramclone-284ee',
    storageBucket: 'flutterinstagramclone-284ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYNZgFMwqxHan1Iah68J63WbGpHq_dgP0',
    appId: '1:643613146881:ios:26d6bed6163f8c0816a500',
    messagingSenderId: '643613146881',
    projectId: 'flutterinstagramclone-284ee',
    storageBucket: 'flutterinstagramclone-284ee.appspot.com',
    iosClientId: '643613146881-8u7dldn55q4mkjej8fmut1srgtslcvp4.apps.googleusercontent.com',
    iosBundleId: 'com.einfp1.flutterInstagramClone',
  );
}
